# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: types.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'types.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btypes.proto\x12\tquiver.v1\"3\n\tEntityKey\x12\x13\n\x0b\x65ntity_type\x18\x01 \x01(\t\x12\x11\n\tentity_id\x18\x02 \x01(\t\"\x83\x01\n\x0f\x46reshnessPolicy\x12\x1d\n\x15max_staleness_seconds\x18\x01 \x01(\x03\x12\x1b\n\x13\x61llow_async_refresh\x18\x02 \x01(\x08\x12\x16\n\x0e\x65rror_on_stale\x18\x03 \x01(\x08\x12\x1c\n\x14require_all_features\x18\x04 \x01(\x08\"I\n\x0eRequestContext\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0e\n\x06\x63\x61ller\x18\x02 \x01(\t\x12\x13\n\x0b\x65nvironment\x18\x03 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'types_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENTITYKEY']._serialized_start=26
  _globals['_ENTITYKEY']._serialized_end=77
  _globals['_FRESHNESSPOLICY']._serialized_start=80
  _globals['_FRESHNESSPOLICY']._serialized_end=211
  _globals['_REQUESTCONTEXT']._serialized_start=213
  _globals['_REQUESTCONTEXT']._serialized_end=286
# @@protoc_insertion_point(module_scope)
