# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: metadata.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'metadata.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emetadata.proto\x12\tquiver.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8c\x04\n\x15ServedFeatureMetadata\x12S\n\x12\x66\x65\x61ture_timestamps\x18\x01 \x03(\x0b\x32\x37.quiver.v1.ServedFeatureMetadata.FeatureTimestampsEntry\x12\x19\n\x11served_from_cache\x18\x02 \x01(\x08\x12\x10\n\x08is_stale\x18\x03 \x01(\x08\x12M\n\x0f\x62\x61\x63kend_sources\x18\x04 \x03(\x0b\x32\x34.quiver.v1.ServedFeatureMetadata.BackendSourcesEntry\x12I\n\rfeature_stats\x18\x05 \x03(\x0b\x32\x32.quiver.v1.ServedFeatureMetadata.FeatureStatsEntry\x1aT\n\x16\x46\x65\x61tureTimestampsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12)\n\x05value\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp:\x02\x38\x01\x1a\x35\n\x13\x42\x61\x63kendSourcesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1aJ\n\x11\x46\x65\x61tureStatsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12$\n\x05value\x18\x02 \x01(\x0b\x32\x15.quiver.v1.BatchStats:\x02\x38\x01\">\n\nBatchStats\x12\x11\n\tnull_rate\x18\x01 \x01(\x01\x12\x0c\n\x04mean\x18\x02 \x01(\x01\x12\x0f\n\x07std_dev\x18\x03 \x01(\x01\"\x99\x02\n\x13\x46\x65\x61tureViewMetadata\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x65ntity_type\x18\x02 \x01(\t\x12\x12\n\nentity_key\x18\x03 \x01(\t\x12/\n\x07\x63olumns\x18\x04 \x03(\x0b\x32\x1e.quiver.v1.FeatureColumnSchema\x12K\n\x0f\x62\x61\x63kend_routing\x18\x05 \x03(\x0b\x32\x32.quiver.v1.FeatureViewMetadata.BackendRoutingEntry\x12\x16\n\x0eschema_version\x18\x06 \x01(\x03\x1a\x35\n\x13\x42\x61\x63kendRoutingEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"I\n\x13\x46\x65\x61tureColumnSchema\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\narrow_type\x18\x02 \x01(\t\x12\x10\n\x08nullable\x18\x03 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'metadata_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SERVEDFEATUREMETADATA_FEATURETIMESTAMPSENTRY']._loaded_options = None
  _globals['_SERVEDFEATUREMETADATA_FEATURETIMESTAMPSENTRY']._serialized_options = b'8\001'
  _globals['_SERVEDFEATUREMETADATA_BACKENDSOURCESENTRY']._loaded_options = None
  _globals['_SERVEDFEATUREMETADATA_BACKENDSOURCESENTRY']._serialized_options = b'8\001'
  _globals['_SERVEDFEATUREMETADATA_FEATURESTATSENTRY']._loaded_options = None
  _globals['_SERVEDFEATUREMETADATA_FEATURESTATSENTRY']._serialized_options = b'8\001'
  _globals['_FEATUREVIEWMETADATA_BACKENDROUTINGENTRY']._loaded_options = None
  _globals['_FEATUREVIEWMETADATA_BACKENDROUTINGENTRY']._serialized_options = b'8\001'
  _globals['_SERVEDFEATUREMETADATA']._serialized_start=63
  _globals['_SERVEDFEATUREMETADATA']._serialized_end=587
  _globals['_SERVEDFEATUREMETADATA_FEATURETIMESTAMPSENTRY']._serialized_start=372
  _globals['_SERVEDFEATUREMETADATA_FEATURETIMESTAMPSENTRY']._serialized_end=456
  _globals['_SERVEDFEATUREMETADATA_BACKENDSOURCESENTRY']._serialized_start=458
  _globals['_SERVEDFEATUREMETADATA_BACKENDSOURCESENTRY']._serialized_end=511
  _globals['_SERVEDFEATUREMETADATA_FEATURESTATSENTRY']._serialized_start=513
  _globals['_SERVEDFEATUREMETADATA_FEATURESTATSENTRY']._serialized_end=587
  _globals['_BATCHSTATS']._serialized_start=589
  _globals['_BATCHSTATS']._serialized_end=651
  _globals['_FEATUREVIEWMETADATA']._serialized_start=654
  _globals['_FEATUREVIEWMETADATA']._serialized_end=935
  _globals['_FEATUREVIEWMETADATA_BACKENDROUTINGENTRY']._serialized_start=882
  _globals['_FEATUREVIEWMETADATA_BACKENDROUTINGENTRY']._serialized_end=935
  _globals['_FEATURECOLUMNSCHEMA']._serialized_start=937
  _globals['_FEATURECOLUMNSCHEMA']._serialized_end=1010
# @@protoc_insertion_point(module_scope)
