# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: observability.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'observability.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13observability.proto\x12\tquiver.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe5\x02\n\x15\x46\x61noutMetricsResponse\x12\x1a\n\x12registry_lookup_ms\x18\x01 \x01(\x01\x12\x17\n\x0f\x63\x61\x63he_lookup_ms\x18\x02 \x01(\x01\x12\x14\n\x0cpartition_ms\x18\x03 \x01(\x01\x12\x13\n\x0b\x64ispatch_ms\x18\x04 \x01(\x01\x12\x18\n\x10\x62\x61\x63kend_redis_ms\x18\x05 \x01(\x01\x12\x18\n\x10\x62\x61\x63kend_delta_ms\x18\x06 \x01(\x01\x12\x1b\n\x13\x62\x61\x63kend_postgres_ms\x18\x07 \x01(\x01\x12\x16\n\x0e\x62\x61\x63kend_max_ms\x18\x08 \x01(\x01\x12\x14\n\x0c\x61lignment_ms\x18\t \x01(\x01\x12\x10\n\x08merge_ms\x18\n \x01(\x01\x12\x15\n\rvalidation_ms\x18\x0b \x01(\x01\x12\x18\n\x10serialization_ms\x18\x0c \x01(\x01\x12\x10\n\x08total_ms\x18\r \x01(\x01\x12\x18\n\x10\x63ritical_path_ms\x18\x0e \x01(\x01\"\'\n\x11GetMetricsRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\"\xaa\x01\n\x12GetMetricsResponse\x12\x31\n\x07metrics\x18\x01 \x01(\x0b\x32 .quiver.v1.FanoutMetricsResponse\x12\x35\n\x11request_timestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x14\n\x0c\x66\x65\x61ture_view\x18\x03 \x01(\t\x12\x14\n\x0c\x65ntity_count\x18\x04 \x01(\x05\x32\x61\n\x14ObservabilityService\x12I\n\nGetMetrics\x12\x1c.quiver.v1.GetMetricsRequest\x1a\x1d.quiver.v1.GetMetricsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'observability_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FANOUTMETRICSRESPONSE']._serialized_start=68
  _globals['_FANOUTMETRICSRESPONSE']._serialized_end=425
  _globals['_GETMETRICSREQUEST']._serialized_start=427
  _globals['_GETMETRICSREQUEST']._serialized_end=466
  _globals['_GETMETRICSRESPONSE']._serialized_start=469
  _globals['_GETMETRICSRESPONSE']._serialized_end=639
  _globals['_OBSERVABILITYSERVICE']._serialized_start=641
  _globals['_OBSERVABILITYSERVICE']._serialized_end=738
# @@protoc_insertion_point(module_scope)
