# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: serving.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "serving.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from . import types_pb2 as types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\rserving.proto\x12\tquiver.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0btypes.proto"\x95\x02\n\x0e\x46\x65\x61tureRequest\x12\x14\n\x0c\x66\x65\x61ture_view\x18\x01 \x01(\t\x12\x15\n\rfeature_names\x18\x02 \x03(\t\x12&\n\x08\x65ntities\x18\x03 \x03(\x0b\x32\x14.quiver.v1.EntityKey\x12)\n\x05\x61s_of\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12-\n\tfreshness\x18\x05 \x01(\x0b\x32\x1a.quiver.v1.FreshnessPolicy\x12*\n\x07\x63ontext\x18\x06 \x01(\x0b\x32\x19.quiver.v1.RequestContext\x12(\n\x06output\x18\x07 \x01(\x0b\x32\x18.quiver.v1.OutputOptions"]\n\rOutputOptions\x12\x1a\n\x12include_timestamps\x18\x01 \x01(\x08\x12\x19\n\x11include_freshness\x18\x02 \x01(\x08\x12\x15\n\rnull_strategy\x18\x03 \x01(\tb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "serving_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_FEATUREREQUEST"]._serialized_start = 75
    _globals["_FEATUREREQUEST"]._serialized_end = 352
    _globals["_OUTPUTOPTIONS"]._serialized_start = 354
    _globals["_OUTPUTOPTIONS"]._serialized_end = 447
# @@protoc_insertion_point(module_scope)
